# Generated by Django 4.0.4 on 2022-05-12 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('authentication', '0005_remove_usersession_session_usersession_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session_key',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
